/**
 * Traduction des erreurs API par code stable (voir
 * djiguigne-backend/core/erreurs.py:MESSAGES_FR pour la source de vérité
 * côté backend -- les codes doivent rester synchronisés des deux côtés).
 *
 * Une seule locale est active pour l'instant (fr), mais la structure est
 * prête pour en ajouter d'autres : il suffit de renseigner LOCALE_ACTIVE
 * et/ou d'ajouter une clé dans MESSAGES ci-dessous.
 */
export type Locale = "fr" | "en";

export const LOCALE_ACTIVE: Locale = "fr";

export const MESSAGES: Record<Locale, Record<string, string>> = {
  fr: {
    AGENT_CREATION_CHAMPS_MANQUANTS: "Remplis au moins la posture générale ou les limites globales.",
    AGENT_INTROUVABLE: "Agent introuvable.",
    AGENT_CREE_MAIS_INDEXATION_ECHEC: "L'agent est créé, mais « {nom} » n'a pas pu être indexé. Réessaie depuis « Mes agents ».",
    PRECISE_MATIERE_AUTRE: "Précise la matière dans \"Autre\".",
    PRECISE_LA_VALEUR_POUR: "Précise la valeur pour {libelle}.",
    EST_DEJA_PRISE_PAR_UNE: "{libelle} est déjà prise par une autre IA.",
    AGENT_MODIFICATION_ERREUR_TECHNIQUE: "Impossible de modifier l'agent (erreur technique). Réessaie dans un instant.",
    AGENT_MODIFICATION_INDISPONIBLE: "Impossible de modifier l'agent pour le moment.",
    AGENT_NOM_DEJA_PROCHE: "Un agent existe déjà avec un nom trop proche (id généré: {agent_id}). Choisis un nom légèrement différent.",
    ARTICLE_SANS_PHOTOS_SUPP: "Un article n'a pas de photos supplémentaires.",
    ARTICLE_SANS_TITRE: "Un article doit avoir un titre.",
    AUCUNE_FORMULE_DETECTEE_DANS_CETTE_IMAGE: "Aucune formule détectée dans cette image.",
    AUCUN_TEXTE_TROUVE_DOCUMENT_SCANNE_IMAGE: "Aucun texte trouvé (document scanné/image sans OCR ?).",
    AUDIO_TROP_LONG_20_MO_MAX: "Audio trop long (20 Mo max).",
    CATEGORIE_INCONNUE: "Catégorie inconnue.",
    CETTE_MATIERE_EST_DEJA_PRISE_PAR: "Cette matière est déjà prise par une autre IA.",
    CETTE_PUBLICATION_NE_T_APPARTIENT_PAS: "Cette publication ne t'appartient pas.",
    CET_AGENT_NE_T_APPARTIENT_PAS: "Cet agent ne t'appartient pas.",
    CE_DOCUMENT_N_APPARTIENT_PAS_A: "Ce document n'appartient pas à cet agent.",
    CONNEXION_INDISPONIBLE: "Connexion à {service} indisponible pour le moment.",
    DOCUMENT_TROP_LOURD_15_MO_MAX: "Document trop lourd (15 Mo max).",
    DONNE_AU_MOINS_UNE_DESCRIPTION_OU: "Donne au moins une description ou un titre.",
    ECHEC_DE_LA_GENERATION_AUDIO_REESSAIE: "Échec de la génération audio, réessaie.",
    ECHEC_DE_LA_GENERATION_DU_DOCUMENT: "Échec de la génération du document, réessaie.",
    ECHEC_DE_LA_LECTURE_DU_DOCUMENT: "Échec de la lecture du document.",
    ECHEC_DE_LA_TRANSCRIPTION_REESSAIE: "Échec de la transcription, réessaie.",
    ECHEC_DE_L_ENREGISTREMENT_DE_L: "Échec de l'enregistrement de l'abonnement.",
    ECHEC_DE_L_ENVOI_POUR_SIGNATURE: "Échec de l'envoi pour signature, réessaie.",
    ECHEC_DE_L_EXPORT_REESSAIE: "Échec de l'export, réessaie.",
    ECHEC_DE_L_EXTRACTION_REESSAIE: "Échec de l'extraction, réessaie.",
    ECHEC_DE_L_UPLOAD_REESSAIE: "Échec de l'upload, réessaie.",
    ECHEC_DU_DESABONNEMENT: "Échec du désabonnement.",
    ECHEC_GENERATION_ARCHIVE: "Échec de la génération de l'archive, réessaie.",
    ECHEC_GENERATION_IMAGE: "Échec de la génération de l'image, réessaie.",
    ECHEC_LANCEMENT_GENERATION_3D: "Échec du lancement de la génération 3D.",
    ECHEC_LANCEMENT_GENERATION_VIDEO: "Échec du lancement de la génération vidéo.",
    ERREUR_INCONNUE: "Une erreur est survenue, réessaie dans un instant.",
    MATIERE_ET_SYSTEM_PROMPT_REQUIS: "La matière et le contenu sont obligatoires.",
    CONTENU_MATIERE_INTROUVABLE: "Contenu introuvable.",
    CODE_INVALIDE: "Ce code ne correspond à aucun contenu.",
    DEJA_RATTACHE_A_CE_CONTENU: "Tu as déjà débloqué ce contenu.",
    RATTACHEMENT_INTROUVABLE: "Rattachement introuvable.",
    FICHIER_AUDIO_VIDE: "Fichier audio vide.",
    FICHIER_TROP_LOURD_50_MO_MAX: "Fichier trop lourd (50 Mo max).",
    FICHIER_VECTORISATION_ECHEC: "« {nom} » n'a pas pu être vectorisé.",
    FICHIER_VECTORISE_MAIS_ECHEC_DU_STOCKAGE: "Fichier vectorisé mais échec du stockage en bibliothèque.",
    FICHIER_VIDE: "Fichier vide.",
    FORMAT_NON_SUPPORTE_JPEG_PNG_OU: "Format non supporté (jpeg, png ou webp uniquement).",
    FORMAT_NON_SUPPORTE_MP4_WEBM_OU: "Format non supporté (mp4, webm ou mov uniquement).",
    FORMAT_NON_SUPPORTE_PDF_WORD_DOCX: "Format non supporté (PDF, Word .docx ou Excel .xlsx uniquement).",
    GENERATION_3D_INDISPONIBLE: "La génération 3D n'est pas encore activée.",
    GENERATION_AUDIO_INDISPONIBLE: "La génération audio n'est pas encore activée sur cette plateforme.",
    GENERATION_VIDEO_INDISPONIBLE: "La génération vidéo n'est pas encore activée.",
    GITHUB_DEPOTS_INDISPONIBLE: "Impossible de récupérer la liste des dépôts.",
    GITHUB_NON_CONNECTE: "Compte GitHub non connecté.",
    HISTOIRE_SANS_COUVERTURE: "Une histoire doit avoir une photo de couverture.",
    HISTOIRE_SANS_TITRE: "Une histoire doit avoir un titre.",
    IMAGE_TROP_LOURDE_5_MO_MAX: "Image trop lourde (5 Mo max).",
    IMPOSSIBLE_DE_CHARGER_CETTE_CONVERSATION: "Impossible de charger cette conversation.",
    IMPOSSIBLE_DE_CHARGER_CET_AGENT_POUR: "Impossible de charger cet agent pour le moment.",
    IMPOSSIBLE_DE_CHARGER_CE_PROFIL_POUR: "Impossible de charger ce profil pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LA_MEMOIRE_POUR: "Impossible de charger la mémoire pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LA_NOTE_POUR: "Impossible de charger la note pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_ABONNES_POUR: "Impossible de charger les abonnés pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_CATEGORIES_POUR: "Impossible de charger les catégories pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_COMMENTAIRES_POUR: "Impossible de charger les commentaires pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_CREATEURS_POUR: "Impossible de charger les créateurs pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_DROITS_POUR: "Impossible de charger les droits pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_MATIERES_POUR: "Impossible de charger les matières pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_MISES_A: "Impossible de charger les mises à jour pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_NOTIFICATIONS_POUR: "Impossible de charger les notifications pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_OUTILS_DISPONIBLES: "Impossible de charger les outils disponibles pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LES_PUBLICATIONS_POUR: "Impossible de charger les publications pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LE_FEED_POUR: "Impossible de charger le feed pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LE_PROFIL_POUR: "Impossible de charger le profil pour le moment.",
    IMPOSSIBLE_DE_CHARGER_LE_REGISTRE_POUR: "Impossible de charger le registre pour le moment.",
    IMPOSSIBLE_DE_CHARGER_L_AGENT_POUR: "Impossible de charger l'agent pour le moment.",
    IMPOSSIBLE_DE_CHARGER_L_HISTORIQUE: "Impossible de charger l'historique.",
    IMPOSSIBLE_DE_CREER_L_AGENT_ERREUR: "Impossible de créer l'agent (erreur technique). Réessaie dans un instant.",
    IMPOSSIBLE_DE_LISTER_LA_BIBLIOTHEQUE_POUR: "Impossible de lister la bibliothèque pour le moment.",
    IMPOSSIBLE_DE_LISTER_LES_DOCUMENTS_POUR: "Impossible de lister les documents pour le moment.",
    IMPOSSIBLE_DE_MARQUER_CETTE_NOTIFICATION_COMME: "Impossible de marquer cette notification comme lue.",
    IMPOSSIBLE_DE_MARQUER_LES_NOTIFICATIONS_COMME: "Impossible de marquer les notifications comme lues.",
    IMPOSSIBLE_DE_METTRE_A_JOUR_LE: "Impossible de mettre à jour le profil pour le moment.",
    IMPOSSIBLE_DE_MODIFIER_LES_DROITS_POUR: "Impossible de modifier les droits pour le moment.",
    IMPOSSIBLE_DE_PUBLIER_LA_MISE_A: "Impossible de publier la mise à jour pour le moment.",
    IMPOSSIBLE_DE_PUBLIER_POUR_LE_MOMENT: "Impossible de publier pour le moment.",
    IMPOSSIBLE_DE_RECUPERER_LE_STATUT: "Impossible de récupérer le statut.",
    IMPOSSIBLE_DE_RETIRER_CE_FOLLOW_POUR: "Impossible de retirer ce follow pour le moment.",
    IMPOSSIBLE_DE_SE_SUIVRE_SOI_MEME: "Impossible de se suivre soi-même.",
    IMPOSSIBLE_DE_SUIVRE_CE_CREATEUR_POUR: "Impossible de suivre ce créateur pour le moment.",
    IMPOSSIBLE_DE_SUPPRIMER_CETTE_PUBLICATION_POUR: "Impossible de supprimer cette publication pour le moment.",
    IMPOSSIBLE_DE_SUPPRIMER_CET_AGENT_POUR: "Impossible de supprimer cet agent pour le moment.",
    IMPOSSIBLE_DE_SUPPRIMER_CE_DOCUMENT: "Impossible de supprimer ce document.",
    IMPOSSIBLE_DE_SUPPRIMER_CE_DOCUMENT_POUR: "Impossible de supprimer ce document pour le moment.",
    IMPOSSIBLE_DE_SUPPRIMER_CE_FICHIER_POUR: "Impossible de supprimer ce fichier pour le moment.",
    IMPOSSIBLE_DE_VERIFIER_CET_AGENT_POUR: "Impossible de vérifier cet agent pour le moment.",
    IMPOSSIBLE_D_AJOUTER_CE_DOCUMENT_POUR: "Impossible d'ajouter ce document pour le moment.",
    IMPOSSIBLE_D_AJOUTER_CE_FICHIER_POUR: "Impossible d'ajouter ce fichier pour le moment.",
    IMPOSSIBLE_D_ANALYSER_CETTE_VIDEO_REESSAIE: "Impossible d'analyser cette vidéo, réessaie.",
    IMPOSSIBLE_D_EFFACER_LA_MEMOIRE_POUR: "Impossible d'effacer la mémoire pour le moment.",
    IMPOSSIBLE_D_EFFACER_LE_PROFIL_POUR: "Impossible d'effacer le profil pour le moment.",
    IMPOSSIBLE_D_ENREGISTRER_LA_MEMOIRE_POUR: "Impossible d'enregistrer la mémoire pour le moment.",
    IMPOSSIBLE_D_ENREGISTRER_LA_NOTE_POUR: "Impossible d'enregistrer la note pour le moment.",
    IMPOSSIBLE_D_ENREGISTRER_LE_COMMENTAIRE_POUR: "Impossible d'enregistrer le commentaire pour le moment.",
    IMPOSSIBLE_D_ENREGISTRER_LE_LIKE_POUR: "Impossible d'enregistrer le like pour le moment.",
    IMPOSSIBLE_D_ENREGISTRER_LE_PROFIL_POUR: "Impossible d'enregistrer le profil pour le moment.",
    IMPOSSIBLE_D_ENVOYER_CE_RETOUR_POUR: "Impossible d'envoyer ce retour pour le moment.",
    LA_MISE_A_JOUR_N_A: "La mise à jour n'a pas pu être créée (erreur technique).",
    LA_NOTE_DOIT_ETRE_COMPRISE_ENTRE: "La note doit être comprise entre 1 et 5.",
    LA_PUBLICATION_N_A_PAS_PU: "La publication n'a pas pu être créée (erreur technique).",
    LE_COMMENTAIRE_NE_PEUT_PAS_ETRE: "Le commentaire ne peut pas être vide.",
    LE_COMMENTAIRE_N_A_PAS_PU: "Le commentaire n'a pas pu être créé (erreur technique).",
    LE_CONTENU_A_ETE_SUPPRIME_MAIS: "Le contenu a été supprimé mais le compte lui-même n'a pas pu être fermé, réessaie.",
    LE_CONTENU_NE_PEUT_PAS_ETRE: "Le contenu ne peut pas être vide.",
    LE_DELAI_D_INACTIVITE_DOIT_ETRE: "Le délai d'inactivité doit être d'au moins 1 jour.",
    LE_DELAI_MINIMUM_ENTRE_DEUX_RELANCES: "Le délai minimum entre deux relances doit être d'au moins 1 jour.",
    LE_NOM_DE_L_AGENT_EST: "Le nom de l'agent est obligatoire.",
    LE_TITRE_NE_PEUT_PAS_ETRE: "Le titre ne peut pas être vide.",
    MATIERE_INCONNUE: "Matière inconnue.",
    NOTIFICATIONS_PUSH_INDISPONIBLE: "Les notifications push ne sont pas encore activées.",
    PHOTOS_SUPP_MAXIMUM: "Maximum {maximum} photos supplémentaires en plus de la couverture.",
    PROFIL_FERMETURE_PARTIELLE: "Le contenu a été supprimé mais le compte lui-même n'a pas pu être fermé, réessaie.",
    PROFIL_INTROUVABLE: "Profil introuvable.",
    PROFIL_MIS_A_JOUR_MAIS_IMPOSSIBLE: "Profil mis à jour mais impossible de le relire pour confirmation.",
    PROFIL_RELECTURE_ECHEC: "Profil mis à jour mais impossible de le relire pour confirmation.",
    PUBLICATION_INTROUVABLE: "Publication introuvable.",
    RECHERCHE_INDISPONIBLE: "La recherche est indisponible pour le moment.",
    REFLEXION_SANS_PHOTO: "Une réflexion ne contient pas de photo.",
    REMPLIS_AU_MOINS_LA_POSTURE_GENERALE: "Remplis au moins la posture générale ou les limites globales.",
    REQUETE_INVALIDE: "La requête envoyée est invalide.",
    RIEN_A_METTRE_A_JOUR_IMAGE: "Rien à mettre à jour (image_vitrine_url et description sont absents).",
    RIEN_A_MODIFIER: "Rien à modifier.",
    RIEN_N_A_ETE_COMPRIS_REESSAIE: "Rien n'a été compris, réessaie plus près du micro.",
    SERVICE_INCONNU: "Service « {service} » inconnu.",
    SESSION_EXPIREE: "Ta session a expiré, reconnecte-toi.",
    SEULS_LES_FICHIERS_PDF_SONT_ACCEPTES: "Seuls les fichiers PDF sont acceptés.",
    SIGNATURE_INDISPONIBLE: "La signature électronique n'est pas encore activée.",
    TOKEN_INVALIDE: "Token invalide ou expiré",
    TOKEN_MANQUANT: "Token d'authentification manquant",
    TYPE_DE_FICHIER_NON_SUPPORTE: "Type de fichier non supporté.",
    TYPE_DE_PUBLICATION_INVALIDE: "Type de publication invalide.",
    VIDEO_ILLISIBLE_REESSAIE_AVEC_UN_AUTRE: "Vidéo illisible, réessaie avec un autre fichier.",
    VIDEO_TROP_LONGUE: "Vidéo trop longue ({duree}s, {maximum}s max).",
    VIDEO_TROP_LOURDE_40_MO_MAX: "Vidéo trop lourde (40 Mo max).",
    VITRINE_ERREUR_TECHNIQUE: "Impossible de mettre à jour la vitrine (erreur technique). Réessaie dans un instant.",
    VITRINE_INDISPONIBLE: "Impossible de mettre à jour la vitrine pour le moment.",
    VITRINE_RIEN_A_METTRE_A_JOUR: "Rien à mettre à jour (image_vitrine_url et description sont absents).",
  },
  en: {
    AGENT_CREATION_CHAMPS_MANQUANTS: "Fill in at least the general posture or the global limits.",
    AGENT_INTROUVABLE: "Agent not found.",
    AGENT_CREE_MAIS_INDEXATION_ECHEC: "The agent was created, but « {nom} » could not be indexed. Try again from « My agents ».",
    PRECISE_MATIERE_AUTRE: "Specify the subject in \"Other\".",
    PRECISE_LA_VALEUR_POUR: "Specify a value for {libelle}.",
    EST_DEJA_PRISE_PAR_UNE: "{libelle} is already taken by another AI.",
    AGENT_MODIFICATION_ERREUR_TECHNIQUE: "Could not update the agent (technical error). Try again in a moment.",
    AGENT_MODIFICATION_INDISPONIBLE: "Could not update the agent right now.",
    AGENT_NOM_DEJA_PROCHE: "An agent already exists with a very similar name (generated id: {agent_id}). Choose a slightly different name.",
    ARTICLE_SANS_PHOTOS_SUPP: "An article can't have extra photos.",
    ARTICLE_SANS_TITRE: "An article must have a title.",
    AUCUNE_FORMULE_DETECTEE_DANS_CETTE_IMAGE: "No formula detected in this image.",
    AUCUN_TEXTE_TROUVE_DOCUMENT_SCANNE_IMAGE: "No text found (scanned document/image without OCR?).",
    AUDIO_TROP_LONG_20_MO_MAX: "Audio too long (20 MB max).",
    CATEGORIE_INCONNUE: "Unknown category.",
    CETTE_MATIERE_EST_DEJA_PRISE_PAR: "This subject is already taken by another AI.",
    CETTE_PUBLICATION_NE_T_APPARTIENT_PAS: "This post doesn't belong to you.",
    CET_AGENT_NE_T_APPARTIENT_PAS: "This agent doesn't belong to you.",
    CE_DOCUMENT_N_APPARTIENT_PAS_A: "This document doesn't belong to this agent.",
    CONNEXION_INDISPONIBLE: "Connection to {service} is unavailable right now.",
    DOCUMENT_TROP_LOURD_15_MO_MAX: "Document too large (15 MB max).",
    DONNE_AU_MOINS_UNE_DESCRIPTION_OU: "Give at least a description or a title.",
    ECHEC_DE_LA_GENERATION_AUDIO_REESSAIE: "Audio generation failed, try again.",
    ECHEC_DE_LA_GENERATION_DU_DOCUMENT: "Document generation failed, try again.",
    ECHEC_DE_LA_LECTURE_DU_DOCUMENT: "Failed to read the document.",
    ECHEC_DE_LA_TRANSCRIPTION_REESSAIE: "Transcription failed, try again.",
    ECHEC_DE_L_ENREGISTREMENT_DE_L: "Failed to save the subscription.",
    ECHEC_DE_L_ENVOI_POUR_SIGNATURE: "Failed to send for signature, try again.",
    ECHEC_DE_L_EXPORT_REESSAIE: "Export failed, try again.",
    ECHEC_DE_L_EXTRACTION_REESSAIE: "Extraction failed, try again.",
    ECHEC_DE_L_UPLOAD_REESSAIE: "Upload failed, try again.",
    ECHEC_DU_DESABONNEMENT: "Failed to unsubscribe.",
    ECHEC_GENERATION_ARCHIVE: "Archive generation failed, try again.",
    ECHEC_GENERATION_IMAGE: "Image generation failed, try again.",
    ECHEC_LANCEMENT_GENERATION_3D: "Failed to start 3D generation.",
    ECHEC_LANCEMENT_GENERATION_VIDEO: "Failed to start video generation.",
    ERREUR_INCONNUE: "Something went wrong, try again in a moment.",
    FICHIER_AUDIO_VIDE: "Empty audio file.",
    FICHIER_TROP_LOURD_50_MO_MAX: "File too large (50 MB max).",
    FICHIER_VECTORISATION_ECHEC: "« {nom} » could not be indexed.",
    FICHIER_VECTORISE_MAIS_ECHEC_DU_STOCKAGE: "File indexed but could not be saved to the library.",
    FICHIER_VIDE: "Empty file.",
    FORMAT_NON_SUPPORTE_JPEG_PNG_OU: "Unsupported format (jpeg, png or webp only).",
    FORMAT_NON_SUPPORTE_MP4_WEBM_OU: "Unsupported format (mp4, webm or mov only).",
    FORMAT_NON_SUPPORTE_PDF_WORD_DOCX: "Unsupported format (PDF, Word .docx or Excel .xlsx only).",
    GENERATION_3D_INDISPONIBLE: "3D generation isn't available yet.",
    GENERATION_AUDIO_INDISPONIBLE: "Audio generation isn't available on this platform yet.",
    GENERATION_VIDEO_INDISPONIBLE: "Video generation isn't available yet.",
    GITHUB_DEPOTS_INDISPONIBLE: "Could not retrieve the list of repositories.",
    GITHUB_NON_CONNECTE: "GitHub account not connected.",
    HISTOIRE_SANS_COUVERTURE: "A story must have a cover photo.",
    HISTOIRE_SANS_TITRE: "A story must have a title.",
    IMAGE_TROP_LOURDE_5_MO_MAX: "Image too large (5 MB max).",
    IMPOSSIBLE_DE_CHARGER_CETTE_CONVERSATION: "Could not load this conversation.",
    IMPOSSIBLE_DE_CHARGER_CET_AGENT_POUR: "Could not load this agent right now.",
    IMPOSSIBLE_DE_CHARGER_CE_PROFIL_POUR: "Could not load this profile right now.",
    IMPOSSIBLE_DE_CHARGER_LA_MEMOIRE_POUR: "Could not load memory right now.",
    IMPOSSIBLE_DE_CHARGER_LA_NOTE_POUR: "Could not load the rating right now.",
    IMPOSSIBLE_DE_CHARGER_LES_ABONNES_POUR: "Could not load followers right now.",
    IMPOSSIBLE_DE_CHARGER_LES_CATEGORIES_POUR: "Could not load categories right now.",
    IMPOSSIBLE_DE_CHARGER_LES_COMMENTAIRES_POUR: "Could not load comments right now.",
    IMPOSSIBLE_DE_CHARGER_LES_CREATEURS_POUR: "Could not load creators right now.",
    IMPOSSIBLE_DE_CHARGER_LES_DROITS_POUR: "Could not load permissions right now.",
    IMPOSSIBLE_DE_CHARGER_LES_MATIERES_POUR: "Could not load subjects right now.",
    IMPOSSIBLE_DE_CHARGER_LES_MISES_A: "Could not load updates right now.",
    IMPOSSIBLE_DE_CHARGER_LES_NOTIFICATIONS_POUR: "Could not load notifications right now.",
    IMPOSSIBLE_DE_CHARGER_LES_OUTILS_DISPONIBLES: "Could not load available tools right now.",
    IMPOSSIBLE_DE_CHARGER_LES_PUBLICATIONS_POUR: "Could not load posts right now.",
    IMPOSSIBLE_DE_CHARGER_LE_FEED_POUR: "Could not load the feed right now.",
    IMPOSSIBLE_DE_CHARGER_LE_PROFIL_POUR: "Could not load the profile right now.",
    IMPOSSIBLE_DE_CHARGER_LE_REGISTRE_POUR: "Could not load the registry right now.",
    IMPOSSIBLE_DE_CHARGER_L_AGENT_POUR: "Could not load the agent right now.",
    IMPOSSIBLE_DE_CHARGER_L_HISTORIQUE: "Could not load history.",
    IMPOSSIBLE_DE_CREER_L_AGENT_ERREUR: "Could not create the agent (technical error). Try again in a moment.",
    IMPOSSIBLE_DE_LISTER_LA_BIBLIOTHEQUE_POUR: "Could not list the library right now.",
    IMPOSSIBLE_DE_LISTER_LES_DOCUMENTS_POUR: "Could not list documents right now.",
    IMPOSSIBLE_DE_MARQUER_CETTE_NOTIFICATION_COMME: "Could not mark this notification as read.",
    IMPOSSIBLE_DE_MARQUER_LES_NOTIFICATIONS_COMME: "Could not mark notifications as read.",
    IMPOSSIBLE_DE_METTRE_A_JOUR_LE: "Could not update the profile right now.",
    IMPOSSIBLE_DE_MODIFIER_LES_DROITS_POUR: "Could not update permissions right now.",
    IMPOSSIBLE_DE_PUBLIER_LA_MISE_A: "Could not publish the update right now.",
    IMPOSSIBLE_DE_PUBLIER_POUR_LE_MOMENT: "Could not publish right now.",
    IMPOSSIBLE_DE_RECUPERER_LE_STATUT: "Could not retrieve the status.",
    IMPOSSIBLE_DE_RETIRER_CE_FOLLOW_POUR: "Could not unfollow right now.",
    IMPOSSIBLE_DE_SE_SUIVRE_SOI_MEME: "You can't follow yourself.",
    IMPOSSIBLE_DE_SUIVRE_CE_CREATEUR_POUR: "Could not follow this creator right now.",
    IMPOSSIBLE_DE_SUPPRIMER_CETTE_PUBLICATION_POUR: "Could not delete this post right now.",
    IMPOSSIBLE_DE_SUPPRIMER_CET_AGENT_POUR: "Could not delete this agent right now.",
    IMPOSSIBLE_DE_SUPPRIMER_CE_DOCUMENT: "Could not delete this document.",
    IMPOSSIBLE_DE_SUPPRIMER_CE_DOCUMENT_POUR: "Could not delete this document right now.",
    IMPOSSIBLE_DE_SUPPRIMER_CE_FICHIER_POUR: "Could not delete this file right now.",
    IMPOSSIBLE_DE_VERIFIER_CET_AGENT_POUR: "Could not verify this agent right now.",
    IMPOSSIBLE_D_AJOUTER_CE_DOCUMENT_POUR: "Could not add this document right now.",
    IMPOSSIBLE_D_AJOUTER_CE_FICHIER_POUR: "Could not add this file right now.",
    IMPOSSIBLE_D_ANALYSER_CETTE_VIDEO_REESSAIE: "Could not analyze this video, try again.",
    IMPOSSIBLE_D_EFFACER_LA_MEMOIRE_POUR: "Could not clear memory right now.",
    IMPOSSIBLE_D_EFFACER_LE_PROFIL_POUR: "Could not clear the profile right now.",
    IMPOSSIBLE_D_ENREGISTRER_LA_MEMOIRE_POUR: "Could not save memory right now.",
    IMPOSSIBLE_D_ENREGISTRER_LA_NOTE_POUR: "Could not save the rating right now.",
    IMPOSSIBLE_D_ENREGISTRER_LE_COMMENTAIRE_POUR: "Could not save the comment right now.",
    IMPOSSIBLE_D_ENREGISTRER_LE_LIKE_POUR: "Could not save the like right now.",
    IMPOSSIBLE_D_ENREGISTRER_LE_PROFIL_POUR: "Could not save the profile right now.",
    IMPOSSIBLE_D_ENVOYER_CE_RETOUR_POUR: "Could not send this feedback right now.",
    LA_MISE_A_JOUR_N_A: "The update could not be created (technical error).",
    LA_NOTE_DOIT_ETRE_COMPRISE_ENTRE: "The rating must be between 1 and 5.",
    LA_PUBLICATION_N_A_PAS_PU: "The post could not be created (technical error).",
    LE_COMMENTAIRE_NE_PEUT_PAS_ETRE: "The comment cannot be empty.",
    LE_COMMENTAIRE_N_A_PAS_PU: "The comment could not be created (technical error).",
    LE_CONTENU_A_ETE_SUPPRIME_MAIS: "The content was deleted but the account itself could not be closed, try again.",
    LE_CONTENU_NE_PEUT_PAS_ETRE: "The content cannot be empty.",
    LE_DELAI_D_INACTIVITE_DOIT_ETRE: "The inactivity delay must be at least 1 day.",
    LE_DELAI_MINIMUM_ENTRE_DEUX_RELANCES: "The minimum delay between two reminders must be at least 1 day.",
    LE_NOM_DE_L_AGENT_EST: "The agent's name is required.",
    LE_TITRE_NE_PEUT_PAS_ETRE: "The title cannot be empty.",
    MATIERE_INCONNUE: "Unknown subject.",
    NOTIFICATIONS_PUSH_INDISPONIBLE: "Push notifications aren't available yet.",
    PHOTOS_SUPP_MAXIMUM: "Maximum {maximum} extra photos in addition to the cover.",
    PROFIL_FERMETURE_PARTIELLE: "The content was deleted but the account itself could not be closed, try again.",
    PROFIL_INTROUVABLE: "Profile not found.",
    PROFIL_MIS_A_JOUR_MAIS_IMPOSSIBLE: "Profile updated, but could not reload it for confirmation.",
    PROFIL_RELECTURE_ECHEC: "Profile updated, but could not reload it for confirmation.",
    PUBLICATION_INTROUVABLE: "Post not found.",
    RECHERCHE_INDISPONIBLE: "Search is unavailable right now.",
    REFLEXION_SANS_PHOTO: "A thought post doesn't include a photo.",
    REMPLIS_AU_MOINS_LA_POSTURE_GENERALE: "Fill in at least the general posture or the global limits.",
    REQUETE_INVALIDE: "The request sent is invalid.",
    RIEN_A_METTRE_A_JOUR_IMAGE: "Nothing to update (image_vitrine_url and description are both missing).",
    RIEN_A_MODIFIER: "Nothing to change.",
    RIEN_N_A_ETE_COMPRIS_REESSAIE: "Nothing was understood, try again closer to the microphone.",
    SERVICE_INCONNU: "Unknown service « {service} ».",
    SESSION_EXPIREE: "Your session has expired, please sign in again.",
    SEULS_LES_FICHIERS_PDF_SONT_ACCEPTES: "Only PDF files are accepted.",
    SIGNATURE_INDISPONIBLE: "Electronic signature isn't available yet.",
    TOKEN_INVALIDE: "Invalid or expired token.",
    TOKEN_MANQUANT: "Missing authentication token.",
    TYPE_DE_FICHIER_NON_SUPPORTE: "Unsupported file type.",
    TYPE_DE_PUBLICATION_INVALIDE: "Invalid post type.",
    VIDEO_ILLISIBLE_REESSAIE_AVEC_UN_AUTRE: "Video unreadable, try again with a different file.",
    VIDEO_TROP_LONGUE: "Video too long ({duree}s, {maximum}s max).",
    VIDEO_TROP_LOURDE_40_MO_MAX: "Video too large (40 MB max).",
    VITRINE_ERREUR_TECHNIQUE: "Could not update the showcase (technical error). Try again in a moment.",
    VITRINE_INDISPONIBLE: "Could not update the showcase right now.",
    VITRINE_RIEN_A_METTRE_A_JOUR: "Nothing to update (image_vitrine_url and description are both missing).",
  },
};

/**
 * Remplace les paramètres {nom_du_champ} d'un message par leurs valeurs
 * (ex: PHOTOS_SUPP_MAXIMUM: "Maximum {maximum} photos..." + { maximum: 6 }).
 */
function interpoler(gabarit: string, params?: Record<string, string | number>): string {
  if (!params) return gabarit;
  return gabarit.replace(/\{(\w+)\}/g, (correspondance, cle) =>
    Object.prototype.hasOwnProperty.call(params, cle) ? String(params[cle]) : correspondance
  );
}

/**
 * Erreur levée par lib/api.ts pour toute réponse HTTP en échec.
 * Porte le `code` stable renvoyé par le backend (voir core/erreurs.py) en
 * plus du message texte, pour permettre la traduction côté front.
 */
export class ErreurApi extends Error {
  code?: string;
  statusCode: number;
  params?: Record<string, string | number>;

  constructor(
    statusCode: number,
    message: string,
    code?: string,
    params?: Record<string, string | number>
  ) {
    super(message);
    this.name = "ErreurApi";
    this.statusCode = statusCode;
    this.code = code;
    this.params = params;
  }
}

/**
 * Message à afficher à l'utilisateur pour une erreur donnée (issue d'un
 * catch autour d'un appel à lib/api.ts, ou de n'importe où ailleurs).
 *
 * Priorité :
 * 1. Le code est connu dans la locale active -> message traduit.
 * 2. Sinon, le message par défaut renvoyé par le backend (déjà en
 *    français, voir core/erreurs.py) -> toujours affichable tel quel.
 * 3. Sinon (erreur JS quelconque, réseau coupé...) -> message générique.
 */
export function messageErreur(e: unknown, locale: Locale = LOCALE_ACTIVE): string {
  if (e instanceof ErreurApi) {
    const gabarit = e.code ? MESSAGES[locale][e.code] : undefined;
    if (gabarit) return interpoler(gabarit, e.params);
    if (e.message) return e.message;
  }
  if (e instanceof Error && e.message) return e.message;
  return MESSAGES[locale].ERREUR_INCONNUE;
}
